// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package usercommand

import (
	"yt-d-rep/github.com/event-sourcing-go/infrastructure/repository/user"
)

// Injectors from wire.go:

func Wire() *handler {
	userRepository := user.ProvideUserRepository()
	usercommandUsecase := ProvideUsecase(userRepository)
	usercommandHandler := ProvideHandler(usercommandUsecase)
	return usercommandHandler
}
